/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows ./models/kart.glb
*/

import { useEffect, useRef } from "react";
import gsap from "gsap";
import { useGLTF, useKeyboardControls, useProgress, useTexture } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { damp } from "three/src/math/MathUtils.js";
import VFXEmitter from "../wawa-vfx/VFXEmitter.tsx";
import { getDriftLevel } from "../constants.js";
import { Glow } from "../particles/drift/glow/Glow.jsx";
import { useGameStore } from "../store.js";
import { Raycaster, Vector3, MathUtils } from "three";
import { KartDust } from "./KartDust.jsx";
import { Sparks } from "../particles/sparks/Sparks.jsx";
import { Skate } from "../particles/drift/Skate/Skate.jsx";
import { Trails } from "../particles/sparks/Trails.jsx";
import { Driver } from "./Driver.jsx";
import { BombModel, MushroomModel, RedShellModel, BlueShellModel, BulletModel } from "./Pickups.jsx";
import { bulletActive } from "../items/homing.js";
import { useGameManager } from "../gameManager.js";
const raycaster = new Raycaster();
const upRaycaster = new Raycaster();

export function Kart({
  speed,
  driftDirection,
  driftPower,
  jumpOffset,
  backWheelOffset,
  inputTurn
}) {
  const { nodes, materials } = useGLTF("/models/kart.glb");

  const wheel3 = useRef(null);
  const wheel2 = useRef(null);
  const wheel1 = useRef(null);
  const wheel0 = useRef(null);
  
  const wheel0Base = useRef(null)
  const wheel1Base = useRef(null)
  const wheel2Base = useRef(null)
  const wheel3Base = useRef(null)
  
  const groupRef = useRef(null);
  const frontWheels = useRef(null);
  const dustWheelStates = useRef([
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
    { position: new Vector3(), shouldEmit: false },
  ]);

  const {progress} = useProgress();
  const bodyRef = useRef(null);

  const leftParticles = useRef(null);
  const rightParticles = useRef(null);

  const sparksLeftRef = useRef(null);
  const sparksRightRef = useRef(null);

  const skate1Ref = useRef(null);
  const skate2Ref = useRef(null);

  const glow1Ref = useRef(null);
  const glow2Ref = useRef(null);

  const smoke1Ref = useRef(null);
  const smoke2Ref = useRef(null);

  const [, get] = useKeyboardControls();
  const yRotation = useRef(0);
  const wheelRef = useRef(null);

  const isDriftingRef = useRef(false);

  const flamePositionLeftRef = useRef(null);
  const flamePositionRightRef = useRef(null);

  const groundMeshes = useRef([]);
  const lastTrackIdRef = useRef(null);
  const boostLaunchVyRef = useRef(0);
  const boostLaunchTimerRef = useRef(null);
  // Per-wheel airborne time: forces landing when flight lasts too long
  // (boost pad 2 gap, big jump) so the kart can never hang in the air.
  const wheelAirTimeRef = useRef([0, 0, 0, 0]);

  useEffect(() => {
    const clearBoost = () => {
      boostLaunchVyRef.current = 0;
      if (boostLaunchTimerRef.current) {
        clearTimeout(boostLaunchTimerRef.current);
        boostLaunchTimerRef.current = null;
      }
    };
    const onLaunch = (e) => {
      clearBoost();
      boostLaunchVyRef.current = e.detail?.launchVy ?? 11;
      boostLaunchTimerRef.current = setTimeout(() => {
        boostLaunchVyRef.current = 0;
        boostLaunchTimerRef.current = null;
      }, 1200);
    };
    // Reset / R must kill any pending launch impulse, otherwise the kart
    // bounces straight back into the air right after Lakitu puts it down.
    const onReset = () => {
      clearBoost();
      wheelFloorY.current = [null, null, null, null];
      wheelAirTimeRef.current = [0, 0, 0, 0];
      for (const w of [wheel0, wheel1, wheel2, wheel3]) {
        if (w.current) {
          w.current.isAirborne = false;
          w.current.verticalVelocity = 0;
        }
      }
    };
    window.addEventListener("mario-kart:launch-jump", onLaunch);
    window.addEventListener("mario-kart:reset", onReset);
    return () => {
      window.removeEventListener("mario-kart:launch-jump", onLaunch);
      window.removeEventListener("mario-kart:reset", onReset);
      clearBoost();
    };
  }, []);

  const setFlamePositions = useGameStore((state) => state.setFlamePositions);
  const setBoostPower = useGameStore((state) => state.setBoostPower);
  const setDriftLevel = useGameStore((state) => state.setDriftLevel);
  const setGroundPosition = useGameStore((state) => state.setGroundPosition);
  const setWheelPositions = useGameStore((state) => state.setWheelPositions);
  const carriedBomb = useGameStore((state) => state.carriedBomb);
  const carriedItem = useGameStore((state) => state.carriedItem);
  const heldMushroom =
    carriedItem &&
    (carriedItem.type === "mushroom" || carriedItem.type === "golden")
      ? carriedItem.type
      : null;
  const heldTriple = carriedItem?.type === "mushroom" && carriedItem?.variant === "triple";
  const selectedDriver = useGameManager((state) => state.selectedDriver);
  // Throw flourish: 0.25s lean punch whenever a carried slot empties (item
  // used/consumed). Driver GLBs have no animation clips, so this procedural
  // nudge on rotation.x (physics only drives .y) is the throw animation.
  const slotSignature = `${carriedBomb ? "b" : ""}:${carriedItem?.type ?? ""}:${carriedItem?.usesLeft ?? ""}`;
  const prevSlotRef = useRef(slotSignature);
  useEffect(() => {
    const prev = prevSlotRef.current;
    prevSlotRef.current = slotSignature;
    // Punch on any use (slot emptied OR charges dropped), never on pickup.
    if (prev !== "::" && prev !== slotSignature && groupRef.current) {
      gsap.fromTo(
        groupRef.current.rotation,
        { x: 0 },
        { x: -0.14, duration: 0.12, yoyo: true, repeat: 1, overwrite: "auto" }
      );
    }
  }, [slotSignature]);
  // Bullet Bill: the kart hides inside the bullet envelope for the ride.
  // Owner-only check (same as PlayerController): a remote ride never hides us.
  const bulletRide = useGameStore((state) => state.bulletRide);
  const onlineSelfId = useGameManager((state) => state.onlineSelfId);
  const myBulletRide =
    bulletRide &&
    bulletRide.ownerId === (onlineSelfId ?? "local") &&
    bulletActive(bulletRide, performance.now())
      ? bulletRide
      : null;
  const starsTex = useTexture("/textures/stars.png");
  const starsGroupRef = useRef(null);
  const { scene } = useThree();
  const camera = useThree((s) => s.camera);
  // Wheel rays traverse scene children on the first frames (before the BVH
  // ground index exists), which includes the dizzy-stars Sprites.
  // Sprite.raycast throws when raycaster.camera is null — provide it here in
  // the render body (not an effect) so it is set before the very first frame.
  raycaster.camera = camera;
  upRaycaster.camera = camera;
  const direction = new Vector3(0, -1, 0)
  const upDirection = new Vector3(0, 1, 0)
  // Last floor height picked per wheel. Used as hysteresis memory so a
  // base-terrain mesh rendered just under the asphalt can never steal the
  // pick while the kart drives on top of it (see pickFloor).
  const wheelFloorY = useRef([null, null, null, null]);
  // Fell into the void (no ground far below): Lakitu-style auto recovery.
  const lastVoidResetRef = useRef(0);

  function rotateWheels(left, right, delta) {
    const rotationSpeed = speed.current * 0.01;
    wheel0.current.rotation.x += rotationSpeed;
    wheel1.current.rotation.x += rotationSpeed;
    wheel2.current.rotation.x += rotationSpeed;
    wheel3.current.rotation.x += rotationSpeed;

    yRotation.current = damp(
      yRotation.current,
      inputTurn.current,
      4, delta
    );

    frontWheels.current.rotation.y = yRotation.current;
    wheelRef.current.rotation.y = yRotation.current * Math.PI * 4;
  }

  function getGroundPosition(wheelBase, wheel, offset = 0, wheelIndex, delta) {
    const cappedDelta = Math.min(Math.max(delta, 0.0005), 0.05);
    const origin = new Vector3();
    wheelBase.current.getWorldPosition(origin);

    // Per-track tuning: Waluigi dirt is rough/bumpy with steep pit walls,
    // Mario asphalt is smooth. Rough needs a wider stick band (no micro
    // sink/float on bumps), stricter floor normals (pit walls are not floor)
    // and a longer down-ray (always find the landing after a jump).
    const activeTrackIdForPhysics =
      useGameManager.getState().selectedTrackId ?? "mario-circuit";
    const isRoughTrack = activeTrackIdForPhysics === "waluigi-stadium";
    const STICK_BAND = isRoughTrack ? 1.0 : 0.45;
    const FLOOR_MIN_Y = isRoughTrack ? 0.4 : 0.15;
    const DOWN_FAR = isRoughTrack ? 80 : 35;
    const UP_FAR = 1.5;
    const GRAVITY = isRoughTrack ? 24 : 18;
    const MAX_AIR_TIME = 2.2;

    // Kart size scale (per-spawn kartScale from the Map Editor). The whole
    // player group is uniformly scaled, so wheel nodes live in scaled local
    // space while the track lives in world space. Skeleton dimensions below
    // are pre-scaled (×ks) and every local<->world handoff divides/multiplies
    // by ks — at ks=1 everything is byte-identical to the original formulas.
    const ks = useGameStore.getState().kartScale ?? 1;
    const invKs = 1 / ks;
    const UP_FAR_SCALED = UP_FAR * ks;

    // Cast downward starting from 2.5 units above the current wheel base
    // so climbs, ramps and elevated bridges ahead can be detected smoothly from above
    const rayOrigin = new Vector3(origin.x, origin.y + 2.5 * ks, origin.z);
    raycaster.set(rayOrigin, direction);
    raycaster.far = DOWN_FAR;
    raycaster.firstHitOnly = true;

    // Only the drivable ground counts here. The track meshes also contain
    // vertical wall faces and tall barrier tops (all named "ground") — those
    // must never set wheel height or the kart teleports/flips.
    const targets =
      groundMeshes.current.length >= 2 ? groundMeshes.current : scene.children;
    const intersects = raycaster.intersectObjects(targets, true);

    const pickFloor = (hits) => {
      const expectedY = origin.y - 0.78 * ks;

      // Usable up-facing surfaces, nearest-first.
      const floors = [];
      for (const hit of hits) {
        if (!hit.object.name.includes("ground")) continue;
        const n = hit.face?.normal;
        // Floor must face upward! Undersides of bridges (n.y < 0) and vertical walls must be rejected.
        // Rough tracks use a stricter threshold so steep dirt pit walls
        // never count as drivable floor (they caused sink/float + sticks).
        if (n && n.y < FLOOR_MIN_Y) continue;
        floors.push(hit);
        if (floors.length >= 8) break;
      }
      if (floors.length === 0) return null;

      // Stick to the surface the wheel is already on: anything within the
      // stick band counts as the same level. Some courses render a
      // base-terrain mesh directly under the asphalt (Mario start straight:
      // terrain at -2.28 vs asphalt at -1.61, and the road itself undulates
      // down to -1.79 elsewhere) — pure "closest to expected" flaps between
      // the stacked layers and the kart ends up driving on the hidden lower
      // one, visibly sunk. The band is wider than any legit per-frame
      // step (ramps/slopes/curbs move the contact patch gradually) but
      // narrower than the ghost-layer gap, so only real level changes
      // (jumps, drops, bridges) fall through to a fresh pick below.
      // Waluigi dirt undulates more per frame, so it uses a wider band.
      const current = wheelFloorY.current[wheelIndex];
      let pool = floors;
      if (Number.isFinite(current)) {
        const stuck = floors.filter(
          (h) => Math.abs(h.point.y - current) <= STICK_BAND
        );
        if (stuck.length > 0) pool = stuck;
      }

      // Among the remaining candidates take the one closest to the expected
      // wheel height (ramps, bridges and landing zones resolve here).
      let best = pool[0];
      let bestDiff = Math.abs(pool[0].point.y - expectedY);
      for (let i = 1; i < pool.length; i++) {
        const diff = Math.abs(pool[i].point.y - expectedY);
        if (diff < bestDiff) {
          bestDiff = diff;
          best = pool[i];
        }
      }
      wheelFloorY.current[wheelIndex] = best.point.y;
      return best;
    };

    let groundHit = pickFloor(intersects);
    if (!groundHit) {
      // Small step-up only (ramp lips, curb edges). The old 6m up-ray
      // teleported karts from pits straight through bridge decks and left
      // them stuck inside geometry / floating.
      upRaycaster.set(origin, upDirection);
      upRaycaster.far = UP_FAR_SCALED;
      upRaycaster.firstHitOnly = true;
      const upHits = upRaycaster.intersectObjects(targets, true);
      for (const hit of upHits) {
        if (!hit.object.name.includes("ground")) continue;
        const n = hit.face?.normal;
        if (n && n.y > FLOOR_MIN_Y) {
          // Only accept a step that is actually close above the wheel.
          if (hit.point.y - origin.y <= UP_FAR_SCALED) {
            groundHit = hit;
            break;
          }
        }
      }
    }
    // Legacy fallback for geometry without usable normals — still reject
    // steep faces so walls can never become the wheel height.
    if (!groundHit) {
      for (const hit of intersects) {
        if (!hit.object.name.includes("ground")) continue;
        const n = hit.face?.normal;
        if (n && Math.abs(n.y) < FLOOR_MIN_Y) continue;
        if (hit.point.y > origin.y + 0.6 * ks) continue;
        groundHit = hit;
        break;
      }
    }
    // Keep the hysteresis memory in sync when a fallback ray provided the
    // hit (pickFloor already stores its own choice).
    if (groundHit) {
      wheelFloorY.current[wheelIndex] = groundHit.point.y;
    }

    if (groundHit) {
      // All heights below are WORLD space; wheel.current.position is scaled
      // local space, so convert on every handoff (local = world / ks).
      // Jump/drift lift offsets scale too, otherwise a 0.4 rear lift rips
      // the wheels off a mini kart (at ks=1 this is exactly the old code).
      const targetW =
        groundHit.point.y +
        0.78 * ks +
        (jumpOffset.current + offset) * ks;
      const prevW = wheel.current.position.y * ks;
      // Clamp vertical speed: on the steep stadium ramp (الصورة) the raw
      // (targetY - prevY) / delta explodes to 60+ when hitting the slope at
      // boost speed, then that insane value becomes the airborne launch
      // velocity -> wheels detach, camera flies up, forced reset. Never let
      // a single frame inject more than a real jump.
      const clampVy = (v) => Math.max(-25, Math.min(14, v));
      if (targetW > prevW + 0.1) {
        // Climbing up a ramp or hill: smoothly and quickly track target height without lagging
        const rawVy = (targetW - prevW) / Math.max(cappedDelta, 0.001);
        wheel.current.verticalVelocity = Math.max(0, Math.min(12, rawVy));
        // Limit climb per frame too so a steep lip can't teleport the wheel
        // 2m in one frame (that teleport is what looked like detachment).
        const maxClimb = (isRoughTrack ? 0.55 : 0.35) * ks;
        const climbedW = damp(prevW, targetW, 24, cappedDelta);
        wheel.current.position.y = Math.min(climbedW, prevW + maxClimb) * invKs;
        wheel.current.isAirborne = false;
        wheelAirTimeRef.current[wheelIndex] = 0;
        // Touching ground kills a stale launch impulse so it can't re-fire.
        if (Math.abs(targetW - prevW) < 0.35) boostLaunchVyRef.current = 0;
      } else if (prevW - targetW > 0.8) {
        // Airborne jump flight over gap / drop: ballistic Mario Kart jump arc!
        if (!wheel.current.isAirborne) {
          wheel.current.isAirborne = true;
          wheelAirTimeRef.current[wheelIndex] = 0;
          const slopeVy = clampVy(wheel.current.verticalVelocity || 0);
          // Ramp launch scales with kart size (a mini kart hitting a ramp
          // at proportional speed gets a proportional hop, not a moon jump).
          const speedVy = speed.current > 20 * ks ? Math.min(10 * ks, speed.current * 0.16) : 4 * ks;
          const boostVy = Math.min(10, boostLaunchVyRef.current || 0);
          wheel.current.verticalVelocity = Math.min(
            14,
            Math.max(0, slopeVy, speedVy, boostVy)
          );
        } else {
          wheelAirTimeRef.current[wheelIndex] += cappedDelta;
        }
        // Long flights get stronger gravity so boost pad 2 / big jumps can
        // never hang in the air forever.
        const airTime = wheelAirTimeRef.current[wheelIndex];
        const gravity = airTime > 1.2 ? GRAVITY + 14 : GRAVITY;
        wheel.current.verticalVelocity -= gravity * cappedDelta;
        // Hard safety: after MAX_AIR_TIME force the touchdown, the landing
        // ray already found the road below (targetY) — hanging is worse
        // than a firm landing.
        if (airTime > MAX_AIR_TIME) {
          wheel.current.position.y = targetW * invKs;
          wheel.current.verticalVelocity = 0;
          wheel.current.isAirborne = false;
          wheelAirTimeRef.current[wheelIndex] = 0;
          boostLaunchVyRef.current = 0;
        } else {
          const nextW = prevW + wheel.current.verticalVelocity * cappedDelta;
          if (nextW <= targetW) {
            // Touchdown on landing road
            wheel.current.position.y = targetW * invKs;
            wheel.current.verticalVelocity = 0;
            wheel.current.isAirborne = false;
            wheelAirTimeRef.current[wheelIndex] = 0;
            boostLaunchVyRef.current = 0;
          } else {
            wheel.current.position.y = nextW * invKs;
          }
        }
      } else {
        const rawFlatVy = (targetW - prevW) / Math.max(cappedDelta, 0.001);
        wheel.current.verticalVelocity = Math.max(-25, Math.min(14, rawFlatVy));
        // Rough dirt dips need a faster follow than 0.1/frame or the kart
        // visibly floats above the ground.
        const maxDrop = (isRoughTrack ? 0.35 : 0.1) * ks;
        wheel.current.position.y = Math.max(targetW, prevW - maxDrop) * invKs;
        wheel.current.isAirborne = false;
        wheelAirTimeRef.current[wheelIndex] = 0;
      }

      wheel.current.lastSafeY = wheel.current.position.y;
    }

    wheel.current.isOnDirt =
      (groundHit?.object.name.includes("dirt") ?? false) &&
      speed.current > 5 &&
      jumpOffset.current === 0;

    if ((wheelIndex === 2 || wheelIndex === 3) && driftPower.current > 0.01 && jumpOffset.current === 0 && offset < 0.05) {
      wheel.current.isOnDirt = true;
    }

    if (!groundHit) {
      if (!wheel.current.isAirborne) {
        wheel.current.isAirborne = true;
        wheelAirTimeRef.current[wheelIndex] = 0;
        const slopeVy = Math.max(-25, Math.min(14, wheel.current.verticalVelocity || 0));
        const speedVy = speed.current > 20 * ks ? Math.min(10 * ks, speed.current * 0.16) : 4 * ks;
        const boostVy = Math.min(10, boostLaunchVyRef.current || 0);
        wheel.current.verticalVelocity = Math.min(14, Math.max(0, slopeVy, speedVy, boostVy));
      } else {
        wheelAirTimeRef.current[wheelIndex] += cappedDelta;
      }
      const airTimeNoGround = wheelAirTimeRef.current[wheelIndex];
      const gravityNoGround = airTimeNoGround > 1.2 ? GRAVITY + 14 : GRAVITY;
      wheel.current.verticalVelocity -= gravityNoGround * cappedDelta;
      wheel.current.position.y += wheel.current.verticalVelocity * cappedDelta * invKs;

      // Hanging over a gap with no road below for too long: force Lakitu
      // rescue instead of floating forever (R was also stuck before).
      if (airTimeNoGround > MAX_AIR_TIME + 0.6) {
        wheelAirTimeRef.current[wheelIndex] = 0;
        wheel.current.verticalVelocity = Math.min(wheel.current.verticalVelocity, -8);
        if (
          useGameManager.getState().gameStarted &&
          performance.now() - lastVoidResetRef.current > 2000
        ) {
          lastVoidResetRef.current = performance.now();
          window.dispatchEvent(new CustomEvent("mario-kart:reset"));
        }
      }

      // Fell into the void: Lakitu-style auto recovery onto the road.
      if (
        origin.y < -25 &&
        performance.now() - lastVoidResetRef.current > 2000 &&
        useGameManager.getState().gameStarted
      ) {
        lastVoidResetRef.current = performance.now();
        window.dispatchEvent(new CustomEvent("mario-kart:reset"));
      }
    }
  }

  function getWheelPositions() {
    const wheelPositions = [wheel0, wheel1, wheel2, wheel3].map(
      (wheel, index) => {
        const position = wheel.current.getWorldPosition(new Vector3());
        const localPos = wheel.current.position;
        dustWheelStates.current[index].position = localPos;
        dustWheelStates.current[index].shouldEmit = wheel.current.isOnDirt;

        index == 2
          ? leftParticles.current.position.set(
              localPos.x - 0.2,
              localPos.y - 0.7,
              localPos.z - 0.2,
            )
          : null;
        index == 3
          ? rightParticles.current.position.set(
              localPos.x + 0.2,
              localPos.y - 0.7,
              localPos.z - 0.2,
            )
          : null;

        return position;
      },
    );
    return wheelPositions;
  }

  // Max visual tilt of the kart body — never let it flip over.
  function moveAndRotateKart(wheelPositions, delta) {
    const a = wheelPositions[0];
    const b = wheelPositions[1];
    const c = wheelPositions[2];
    const d = wheelPositions[3];

    let pitch = (c.y + d.y - (a.y + b.y)) * 0.5;
    let roll = (b.y - a.y + d.y - c.y) * 0.5;
    if (!Number.isFinite(pitch)) pitch = 0;
    if (!Number.isFinite(roll)) roll = 0;
    pitch = MathUtils.clamp(pitch, -0.45, 0.45);
    roll = MathUtils.clamp(roll, -0.45, 0.45);

    // Outlier rejection: if one wheel spikes 3m+ above the rest (wrong deck
    // / ramp-top pick mid-flight) the mean would yank the body + camera up
    // and the wheels look detached. Use the median in that case so a single
    // bad sample can't move the kart.
    const ys = [a.y, b.y, c.y, d.y].filter(Number.isFinite).sort((x, y) => x - y);
    let baseY = (a.y + b.y + c.y + d.y) / 4;
    if (ys.length === 4 && ys[3] - ys[0] > 3) {
      baseY = (ys[1] + ys[2]) / 2;
    }
    // World-space body height; the body node lives in scaled local space.
    const ksBody = useGameStore.getState().kartScale ?? 1;
    const averageYPos = 0.65 * ksBody + baseY;
    setGroundPosition(averageYPos);

    // Damped tilt so a single bad wheel sample can't snap the kart over.
    bodyRef.current.rotation.x = damp(
      bodyRef.current.rotation.x,
      pitch,
      8,
      delta
    );

    bodyRef.current.rotation.z = damp(
      bodyRef.current.rotation.z,
      roll,
      8,
      delta
    );

    bodyRef.current.position.y = averageYPos / ksBody + jumpOffset.current * 0.1;
  }
  useFrame((_, delta) => {
    // Dizzy stars orbit while the explosion stun is active.
    if (starsGroupRef.current) {
      const stunned =
        performance.now() < useGameStore.getState().stunUntil;
      starsGroupRef.current.visible = stunned;
      if (stunned) {
        starsGroupRef.current.rotation.y += delta * 7;
        starsGroupRef.current.position.y =
          1.35 + Math.sin(performance.now() / 90) * 0.08;
      }
    }
    if (wheel0.current && wheel1.current && wheel2.current && wheel3.current) {
      // One-shot rescue snap from Reset: place every wheel on the rescued
      // road level at once. The body + ray origins follow the wheels in this
      // same frame (see below), so the next raycasts already start from the
      // new level instead of dragging the kart back down into the pit.
      const snapY = useGameStore.getState().wheelSnapY;
      if (snapY !== null && snapY !== undefined) {
        useGameStore.getState().setWheelSnapY(null);
        if (Number.isFinite(snapY)) {
          // Scaled local space: local = world / ks, plus the fixed 0.78
          // local offset (it absorbs the -0.5 group shift, exactly like the
          // touchdown path above — at ks=1 this is snapY + 0.78 as before).
          const ksSnap = useGameStore.getState().kartScale ?? 1;
          for (const wheel of [wheel0, wheel1, wheel2, wheel3]) {
            if (wheel.current) {
              wheel.current.position.y = snapY / ksSnap + 0.78;
              wheel.current.verticalVelocity = 0;
              wheel.current.isAirborne = false;
              wheel.current.lastSafeY = snapY / ksSnap + 0.78;
            }
          }
          // Teleported to a new level: drop the floor memory so the next
          // pick is fresh instead of sticking to the old surface.
          wheelFloorY.current = [snapY, snapY, snapY, snapY];
          wheelAirTimeRef.current = [0, 0, 0, 0];
          boostLaunchVyRef.current = 0;
          if (boostLaunchTimerRef.current) {
            clearTimeout(boostLaunchTimerRef.current);
            boostLaunchTimerRef.current = null;
          }
        }
      }
      const activeTrackId = useGameManager.getState().selectedTrackId;
      if (lastTrackIdRef.current !== activeTrackId) {
        lastTrackIdRef.current = activeTrackId;
        groundMeshes.current = [];
        wheelFloorY.current = [null, null, null, null];
      }
      if (groundMeshes.current.length < 2) {
        scene.traverse((obj) => {
          if (
            obj.isMesh &&
            obj.name.includes("ground") &&
            obj.geometry?.boundsTree
          ) {
            groundMeshes.current.push(obj);
          }
        });
      }
      const isDrifting = !!driftDirection.current && jumpOffset.current === 0;
      const { left, right } = get();

      rotateWheels(left, right, delta);

      getGroundPosition(wheel0Base, wheel0, backWheelOffset.current.right, 0, delta);
      getGroundPosition(wheel1Base, wheel1, backWheelOffset.current.left, 1, delta);
      getGroundPosition(wheel2Base, wheel2, backWheelOffset.current.right, 2, delta);
      getGroundPosition(wheel3Base, wheel3, backWheelOffset.current.left, 3, delta);

      const wheelPositions = getWheelPositions();

      setWheelPositions([...wheelPositions, bodyRef.current]);
      moveAndRotateKart(wheelPositions, delta);

      if (speed.current > 15) {
        smoke1Ref.current?.stopEmitting();
        smoke2Ref.current?.stopEmitting();
      } else {
        smoke1Ref.current?.startEmitting();
        smoke2Ref.current?.startEmitting();
      }

      groupRef.current.rotation.y = damp(
        groupRef.current.rotation.y,
        driftDirection.current * 0.4,
        4, delta
      );

      const driftLevel = getDriftLevel(driftPower.current);
      if (isDrifting !== isDriftingRef.current) {
        isDriftingRef.current = isDrifting;
        if (isDrifting) {
          sparksLeftRef?.current?.setEmitState(true);
          sparksRightRef?.current?.setEmitState(true);
          glow1Ref?.current?.setOpacity(1);
          glow2Ref?.current?.setOpacity(1);
          skate1Ref?.current?.setOpacity(1);
          skate2Ref?.current?.setOpacity(1);
        } else {
          sparksLeftRef?.current?.setEmitState(false);
          sparksRightRef?.current?.setEmitState(false);
          glow1Ref?.current?.setOpacity(0);
          glow2Ref?.current?.setOpacity(0);
          skate1Ref?.current?.setOpacity(0);
          skate2Ref?.current?.setOpacity(0);
        }
      }

      bodyRef.current.isDrifting = isDrifting;
      if (isDrifting) {
        glow1Ref?.current?.setColor(driftLevel.color);
        glow2Ref?.current?.setColor(driftLevel.color);
        glow1Ref?.current?.setLevel(driftLevel.threshold);
        glow2Ref?.current?.setLevel(driftLevel.threshold);

        sparksLeftRef?.current?.setColor(driftLevel.color);
        sparksRightRef?.current?.setColor(driftLevel.color);
      }
      setDriftLevel(driftLevel);

      setFlamePositions([
        flamePositionLeftRef.current.getWorldPosition(new Vector3()),
        flamePositionRightRef.current.getWorldPosition(new Vector3()),
      ]);
      setBoostPower(driftLevel.threshold / 2);
    }
  });

  useEffect(() => {
    if (glow1Ref.current && glow2Ref.current && bodyRef.current) {
      glow1Ref?.current?.setOpacity(0);
      glow2Ref?.current?.setOpacity(0);
    }
  }, []);
  return (
    <>
      {/* <pointLight intensity={2000} position={[0, 10, 0]}/> */}

      <group key={progress} ref={groupRef} dispose={null}>
        {myBulletRide && (
          <group rotation-y={Math.PI}>
            <BulletModel position={[0, 0.6, 0]} />
          </group>
        )}
        <group rotation-y={Math.PI} visible={!myBulletRide}>
          <group ref={leftParticles}>
            <Glow ref={glow1Ref} driftDirection={driftDirection} />
            <Sparks ref={sparksLeftRef} />
            <Trails />

            <group position={[0.15, 0.2, -0.2]}>
              <Skate ref={skate1Ref} />
            </group>
          </group>
          <group ref={rightParticles}>
            <Glow ref={glow2Ref} driftDirection={driftDirection} />
            <Sparks ref={sparksRightRef} left={true} />
            <Trails left={true} />
            <group position={[-0.15, 0.2, -0.2]}>
              <Skate ref={skate2Ref} />
            </group>
          </group>
        </group>

        <group position-y={-0.5} scale={1} rotation-y={Math.PI} visible={!myBulletRide}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body.geometry}
            material={materials.m_Body}
            ref={bodyRef}
          >
            <group ref={wheel2Base} position={[-.77, 0, -.7]} />
            <group ref={wheel3Base} position={[0.77, 0, -0.7]} />
            <group ref={wheel1Base} position={[0.7, 0, 0.7]} />
            <group ref={wheel0Base} position={[-0.7, 0, 0.7]} />
            <KartDust wheelStates={dustWheelStates.current} />
            <mesh
              ref={wheelRef}
              castShadow
              receiveShadow
              geometry={nodes.d_wheel.geometry}
              material={materials.m_Body}
              position={[0, 0.355, 0.542]}
              rotation={[-1.134, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.booster.geometry}
              material={materials.m_Body}
              position={[0, 0.25, -0.55]}
              rotation={[0.279, 0, 0]}
            />
            {/* Driver: seated behind the steering wheel (front is +Z here).
                Lower body is sunk into the kart body; torso/head/arms show.
                If he faces backwards, set rotation-y to Math.PI. */}
            <group position={[0, 0.45, -0.1]} scale={0.7}>
              <Driver character={selectedDriver} />
            </group>
            {/* Carried bomb, visible on the back until dropped with G */}
            {carriedBomb && (
              <group position={[0, 1.0, -1.2]} scale={0.5}>
                <BombModel />
              </group>
            )}
            {/* Carried mushroom-family item (same mount point as the bomb).
                Mushroom GLB runs large — 0.22 keeps it kart-proportioned.
                Triple renders three small ones circling the kart. */}
            {heldMushroom && !heldTriple && (
              <group position={[0, 1.0, -1.2]} scale={1}>
                <MushroomModel gold={heldMushroom === "golden"} />
              </group>
            )}
            {heldTriple && (
              <group position={[0, 1.0, -1.2]}>
                {[90, 210, 330].map((deg) => {
                  const a = (deg * Math.PI) / 180;
                  return (
                    <group
                      key={deg}
                      position={[Math.cos(a) * 1.1, 0, Math.sin(a) * 1.1]}
                    >
                      <MushroomModel />
                    </group>
                  );
                })}
              </group>
            )}
            {/* Carried red shell */}
            {carriedItem?.type === "red" && (
              <group position={[0, 1.0, -1.2]}>
                <RedShellModel />
              </group>
            )}
            {/* Carried blue shell */}
            {carriedItem?.type === "blue" && (
              <group position={[0, 1.0, -1.2]}>
                <BlueShellModel />
              </group>
            )}
            {/* Dizzy stars while stunned by an explosion */}
            <group ref={starsGroupRef} position={[0, 1.35, -0.1]} visible={false}>
              {[0, 1, 2, 3, 4, 5].map((i) => {
                const a = (i / 6) * Math.PI * 2;
                return (
                  <sprite
                    key={i}
                    position={[Math.cos(a) * 0.9, (i % 2) * 0.25, Math.sin(a) * 0.9]}
                    scale={[0.45, 0.45, 1]}
                  >
                    <spriteMaterial
                      map={starsTex}
                      transparent
                      depthWrite={false}
                    />
                  </sprite>
                );
              })}
            </group>
            <group
              position={[0.5, 0.65, -1.5]}
              rotation-x={-Math.PI / 9}
              ref={flamePositionLeftRef}
            >
              <VFXEmitter
                ref={smoke1Ref}
                emitter="smoke"
                settings={{
                  duration: 0.02,
                  delay: 0.1,
                  nbParticles: 1,
                  spawnMode: "time",
                  loop: true,
                  startPositionMin: [0, 0, 0],
                  startPositionMax: [0, 0, 0],
                  startRotationMin: [0, 0, -1],
                  startRotationMax: [0, 0, 1],
                  particlesLifetime: [0.2, 0.4],
                  speed: [0.5, 1],
                  colorStart: ["#ffffff"],
                  directionMin: [-0.1, 0, 0],
                  directionMax: [0.1, 0.01, 0.5],
                  rotationSpeedMin: [0, 0, -1],
                  rotationSpeedMax: [0, 0, 1],
                  size: [0.5, 1],
                }}
              />
            </group>
            <group
              position={[-0.5, 0.65, -1.5]}
              rotation-x={-Math.PI / 9}
              ref={flamePositionRightRef}
            >
              <VFXEmitter
                ref={smoke2Ref}
                emitter="smoke"
                settings={{
                  duration: 0.02,
                  delay: 0.1,
                  nbParticles: 1,
                  spawnMode: "time",
                  loop: true,
                  startPositionMin: [0, 0, 0],
                  startPositionMax: [0, 0, 0],
                  startRotationMin: [0, 0, -1],
                  startRotationMax: [0, 0, 1],
                  particlesLifetime: [0.2, 0.4],
                  speed: [0.5, 1],
                  colorStart: ["#ffffff"],
                  directionMin: [-0.1, 0, 0],
                  directionMax: [0.1, 0.01, 0.5],
                  rotationSpeedMin: [0, 0, -1],
                  rotationSpeedMax: [0, 0, 1],
                  size: [0.5, 1],
                }}
              />
            </group>
          </mesh>

          <mesh
            ref={wheel2}
            castShadow
            receiveShadow
            geometry={nodes.wheel_2.geometry}
            material={materials.m_Tire}
            position={[-0.77, -0.137, -0.7]}
            layers={1}
            />
          <mesh
            ref={wheel3}
            castShadow
            receiveShadow
            geometry={nodes.wheel_3.geometry}
            material={materials.m_Tire}
            position={[0.77, -0.137, -0.7]}
            layers={1}
            />
          <group ref={frontWheels}>
            <mesh
              ref={wheel1}
              castShadow
              receiveShadow
              geometry={nodes.wheel_1.geometry}
              material={materials.m_Tire}
              position={[0.7, -0.2, 0.7]}
              layers={1}
              />
            <mesh
              ref={wheel0}
              castShadow
              receiveShadow
              geometry={nodes.wheel_0.geometry}
              material={materials.m_Tire}
              position={[-0.7, -0.2, 0.7]}
              layers={1}
            />
          </group>

          {/* <mesh castShadow receiveShadow geometry={nodes.shape.geometry} material={materials['default']} /> */}
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/models/kart.glb");
