import { create } from "zustand";
import { spinWindows } from "./items/homing.js";
import { publishOnlineRaceEvent } from "./onlineRaceTransport.js";

// THE single hit path (v3 §5, frozen signature): spins the LOCAL kart and
// opens hit-invulnerability. Remote victims call this on receipt — the owner
// never stuns remotes directly. Also mirrors stunUntil for legacy readers.
export const applySpin = ({ victim = "self", heavy = false, ms = null, now = performance.now() } = {}) => {
  if (victim !== "self") return false;
  const st = useGameStore.getState();
  const w = spinWindows({ heavy, ms, now });
  st.setSpin({ until: w.spinUntil, heavy: !!heavy });
  st.setInvulnUntil(w.invulnUntil);
  st.setStunUntil(w.spinUntil);
  return true;
};

// Triple-red orbit absorb (§4.3 matrix): eats one orbiting shell instead of
// the hit. Returns true when absorbed (caller skips stun/shove).
export const absorbWithOrbit = (incomingKind, notify = true) => {
  const st = useGameStore.getState();
  const held = st.carriedItem;
  if (
    held?.type !== "red" ||
    held?.variant !== "triple" ||
    (held?.usesLeft ?? 0) <= 0
  ) {
    return false;
  }
  // Matrix lives in homing.absorbedByOrbit — replicate the two allowed
  // kinds here to keep store.js free of extra imports (same rule).
  if (incomingKind !== "red" && incomingKind !== "bomb") return false;
  const left = held.usesLeft - 1;
  const next = left > 0 ? { ...held, usesLeft: left } : null;
  st.setCarriedItem(next);
  if (notify) {
    publishOnlineRaceEvent({
      type: "item:carried",
      itemType: next ? next.type : null,
      variant: next ? next.variant ?? "single" : null,
      // Remotes track the orbit count + golden window from these.
      usesLeft: next && Number.isInteger(next.usesLeft) ? next.usesLeft : null,
      windowUntil: next && Number.isFinite(next.windowUntil) ? next.windowUntil : null,
    });
  }
  return true;
};

export const useGameStore = create((set) => ({
  playerPosition: null,
  setPlayerPosition: (position) => set({ playerPosition: position }),
  speed: null,
  setSpeed: (speed) => set({ speed: speed }),
  flamePositions: null,
  setFlamePositions: (positions) => set({ flamePositions: positions }),
  boostPower: 0,
  setBoostPower: (power) => set({ boostPower: power }),
  isBoosting : false,
  setIsBoosting: (isBoosting) => set({ isBoosting }),
  driftLevel: null,
  setDriftLevel: (level) => set({ driftLevel: level }),
  groundPosition: null,
  setGroundPosition: (groundPosition) => set({groundPosition: groundPosition}),
  // One-shot wheel-height snap consumed by the Kart on the next frame.
  // Reset sets it to the rescued road level so the wheels (and the body +
  // ray origins following them) jump to the new level together — e.g. from
  // the pit floor onto the deck above it — instead of re-acquiring the old
  // level underneath. Null when there is nothing to snap.
  wheelSnapY: null,
  setWheelSnapY: (wheelSnapY) => set({ wheelSnapY }),
  wheelPositions: null,
  setWheelPositions: (wheelPositions) => set({wheelPositions: wheelPositions}),
  body: null,
  setBody: (body) => set({body: body}),
  joystick: {x: 0, y: 0, distance: 0},
  setJoystick: (joystick) => set({ joystick: joystick }),
  jumpButtonPressed: false,
  setJumpButtonPressed: (pressed) => set({ jumpButtonPressed: pressed }),
  noiseTexture: null,
  setNoiseTexture: (noiseTexture) => set({noiseTexture: noiseTexture}),
  gamepad: null,
  setGamepad: (gamepad) => set({gamepad: gamepad}),
  isOnDirt:null,
  setIsOnDirt: (isOnDirt) => set({isOnDirt: isOnDirt}),
  // Wall collision: flat XZ segments {ax, az, bx, bz} in world space.
  // Generated by TrackWalls from the track road mesh + outer bounds.
  wallSegments: [],
  setWallSegments: (wallSegments) => set({ wallSegments }),
  // Pre-processed road geometry {triangles, boundaryEdges, minX, maxX, minZ, maxZ}
  roadMapData: null,
  setRoadMapData: (roadMapData) => set({ roadMapData }),
  // --- Item / bomb battle state ---
  playerRotationY: 0,
  setPlayerRotationY: (playerRotationY) => set({ playerRotationY }),
  // Per-spawn kart size multiplier (from the active spawn slot, editable in
  // the Map Editor). 1 = normal size. The Kart wheel rig multiplies its
  // ground offsets by this so scaled karts still sit on the road correctly.
  kartScale: 1,
  setKartScale: (kartScale) => set({ kartScale }),
  carriedBomb: false,
  setCarriedBomb: (carriedBomb) => set({ carriedBomb }),
  // Battle-items slot (v3): {type, variant, usesLeft} (+windowUntil golden).
  // One slot shared with the bomb.
  carriedItem: null,
  setCarriedItem: (carriedItem) => set({ carriedItem }),
  // Roulette spin: {type, startedAt} while icons cycle. Commits to
  // carriedItem when the spin locks — the item appears/works only then.
  roulette: null,
  setRoulette: (roulette) => set({ roulette }),
  // Item boxes on track: [{id, x, y, z, active, respawnAt}]
  itemBoxes: [],
  setItemBoxes: (itemBoxes) => set({ itemBoxes }),
  // Dropped live bombs: [{id, x, y, z, at}]
  droppedBombs: [],
  setDroppedBombs: (droppedBombs) => set({ droppedBombs }),
  // Explosions to render/react to: [{id, x, y, z, at}]
  explosions: [],
  setExplosions: (explosions) => set({ explosions }),
  // Live homing shells (red/blue): [{id, kind, x,y,z, dx,dz, targetId, owner, ownerId, at}]
  // Owner simulates + detects hits; remotes render the same entries.
  activeShells: [],
  setActiveShells: (activeShells) => set({ activeShells }),
  // Bullet Bill ride: {rideId, until} while active. PlayerController reads it
  // every frame for autopilot speed/steering + invincibility.
  bulletRide: null,
  setBulletRide: (bulletRide) => set({ bulletRide }),
  // Blooper ink: performance.now() timestamp the overlay fades until.
  blooperUntil: 0,
  setBlooperUntil: (blooperUntil) => set({ blooperUntil }),
  // Blooper squirt visual: {x,y,z,until} for the ~1s fire flourish.
  blooperSquirt: null,
  setBlooperSquirt: (blooperSquirt) => set({ blooperSquirt }),
  // Blue-shell warning: {since} while the target-only alarm loops.
  blueWarning: null,
  setBlueWarning: (blueWarning) => set({ blueWarning }),
  // Distance driven this race (world units, teleports capped out). Breaks
  // lap ties for position ranks. No subscribers — read via getState.
  selfDistance: 0,
  addSelfDistance: (d) =>
    set((s) => ({
      selfDistance:
        s.selfDistance + (Number(d) > 0 ? Math.min(30, Number(d)) : 0),
    })),
  // Mushroom boost window end (performance.now). While active the kart
  // targets exactly 1.5x max (no stacking, eases out naturally after).
  shroomUntil: 0,
  setShroomUntil: (shroomUntil) => set({ shroomUntil }),
  // Timestamp (performance.now) until which the kart is stunned.
  stunUntil: 0,
  setStunUntil: (stunUntil) => set({ stunUntil }),
  // Spin-out (v3 §5): {until, heavy} while tumbling; inputs dead.
  spin: null,
  setSpin: (spin) => set({ spin }),
  // Hit-invulnerability window end (shells/bombs pass through).
  invulnUntil: 0,
  setInvulnUntil: (invulnUntil) => set({ invulnUntil }),
  // Release-time spawn queue: [{kind, backward, pressAt, releaseAt}].
  // Press commits instantly; the projectile appears at release.
  pendingSpawns: [],
  setPendingSpawns: (pendingSpawns) => set({ pendingSpawns }),
  // Fresh session state: called on start/exit so stale boxes, live bombs,
  // explosions, carried bombs and stuns never leak into the next run.
  resetBattleState: () =>
    set({
      carriedBomb: false,
      carriedItem: null,
      roulette: null,
      activeShells: [],
      bulletRide: null,
      blooperUntil: 0,
      blooperSquirt: null,
      blueWarning: null,
      selfDistance: 0,
      shroomUntil: 0,
      spin: null,
      invulnUntil: 0,
      pendingSpawns: [],
      itemBoxes: [],
      droppedBombs: [],
      explosions: [],
      stunUntil: 0,
    }),
}));
