import { create } from "zustand";

export const useGameStore = create((set) => ({
  playerPosition: null,
  setPlayerPosition: (position) => set({ playerPosition: position }),
  speed: null,
  setSpeed: (speed) => set({ speed: speed }),
  flamePositions: null,
  setFlamePositions: (positions) => set({ flamePositions: positions }),
  boostPower: 0,
  setBoostPower: (power) => set({ boostPower: power }),
  isBoosting : false,
  setIsBoosting: (isBoosting) => set({ isBoosting }),
  driftLevel: null,
  setDriftLevel: (level) => set({ driftLevel: level }),
  groundPosition: null,
  setGroundPosition: (groundPosition) => set({groundPosition: groundPosition}),
  wheelPositions: null,
  setWheelPositions: (wheelPositions) => set({wheelPositions: wheelPositions}),
  body: null,
  setBody: (body) => set({body: body}),
  joystick: {x: 0, y: 0, distance: 0},
  setJoystick: (joystick) => set({ joystick: joystick }),
  jumpButtonPressed: false,
  setJumpButtonPressed: (pressed) => set({ jumpButtonPressed: pressed }),
  noiseTexture: null,
  setNoiseTexture: (noiseTexture) => set({noiseTexture: noiseTexture}),
  gamepad: null,
  setGamepad: (gamepad) => set({gamepad: gamepad}),
  isOnDirt:null,
  setIsOnDirt: (isOnDirt) => set({isOnDirt: isOnDirt}),
  // Wall collision: flat XZ segments {ax, az, bx, bz} in world space.
  // Generated by TrackWalls from the track road mesh + outer bounds.
  wallSegments: [],
  setWallSegments: (wallSegments) => set({ wallSegments }),
  // Pre-processed road geometry {triangles, boundaryEdges, minX, maxX, minZ, maxZ}
  roadMapData: null,
  setRoadMapData: (roadMapData) => set({ roadMapData }),
  // --- Item / bomb battle state ---
  playerRotationY: 0,
  setPlayerRotationY: (playerRotationY) => set({ playerRotationY }),
  carriedBomb: false,
  setCarriedBomb: (carriedBomb) => set({ carriedBomb }),
  // Item boxes on track: [{id, x, y, z, active, respawnAt}]
  itemBoxes: [],
  setItemBoxes: (itemBoxes) => set({ itemBoxes }),
  // Dropped live bombs: [{id, x, y, z, at}]
  droppedBombs: [],
  setDroppedBombs: (droppedBombs) => set({ droppedBombs }),
  // Explosions to render/react to: [{id, x, y, z, at}]
  explosions: [],
  setExplosions: (explosions) => set({ explosions }),
  // Timestamp (performance.now) until which the kart is stunned.
  stunUntil: 0,
  setStunUntil: (stunUntil) => set({ stunUntil }),
  // Fresh session state: called on start/exit so stale boxes, live bombs,
  // explosions, carried bombs and stuns never leak into the next run.
  resetBattleState: () =>
    set({
      carriedBomb: false,
      itemBoxes: [],
      droppedBombs: [],
      explosions: [],
      stunUntil: 0,
    }),
}));
