import { create } from "zustand";

export const useGameStore = create((set) => ({
  playerPosition: null,
  setPlayerPosition: (position) => set({ playerPosition: position }),
  speed: null,
  setSpeed: (speed) => set({ speed: speed }),
  flamePositions: null,
  setFlamePositions: (positions) => set({ flamePositions: positions }),
  boostPower: 0,
  setBoostPower: (power) => set({ boostPower: power }),
  isBoosting : false,
  setIsBoosting: (isBoosting) => set({ isBoosting }),
  driftLevel: null,
  setDriftLevel: (level) => set({ driftLevel: level }),
  groundPosition: null,
  setGroundPosition: (groundPosition) => set({groundPosition: groundPosition}),
  // One-shot wheel-height snap consumed by the Kart on the next frame.
  // Reset sets it to the rescued road level so the wheels (and the body +
  // ray origins following them) jump to the new level together — e.g. from
  // the pit floor onto the deck above it — instead of re-acquiring the old
  // level underneath. Null when there is nothing to snap.
  wheelSnapY: null,
  setWheelSnapY: (wheelSnapY) => set({ wheelSnapY }),
  wheelPositions: null,
  setWheelPositions: (wheelPositions) => set({wheelPositions: wheelPositions}),
  body: null,
  setBody: (body) => set({body: body}),
  joystick: {x: 0, y: 0, distance: 0},
  setJoystick: (joystick) => set({ joystick: joystick }),
  jumpButtonPressed: false,
  setJumpButtonPressed: (pressed) => set({ jumpButtonPressed: pressed }),
  noiseTexture: null,
  setNoiseTexture: (noiseTexture) => set({noiseTexture: noiseTexture}),
  gamepad: null,
  setGamepad: (gamepad) => set({gamepad: gamepad}),
  isOnDirt:null,
  setIsOnDirt: (isOnDirt) => set({isOnDirt: isOnDirt}),
  // Wall collision: flat XZ segments {ax, az, bx, bz} in world space.
  // Generated by TrackWalls from the track road mesh + outer bounds.
  wallSegments: [],
  setWallSegments: (wallSegments) => set({ wallSegments }),
  // Pre-processed road geometry {triangles, boundaryEdges, minX, maxX, minZ, maxZ}
  roadMapData: null,
  setRoadMapData: (roadMapData) => set({ roadMapData }),
  // --- Item / bomb battle state ---
  playerRotationY: 0,
  setPlayerRotationY: (playerRotationY) => set({ playerRotationY }),
  // Per-spawn kart size multiplier (from the active spawn slot, editable in
  // the Map Editor). 1 = normal size. The Kart wheel rig multiplies its
  // ground offsets by this so scaled karts still sit on the road correctly.
  kartScale: 1,
  setKartScale: (kartScale) => set({ kartScale }),
  carriedBomb: false,
  setCarriedBomb: (carriedBomb) => set({ carriedBomb }),
  // Battle-items slot (Task 1 foundation): one slot shared with the bomb.
  // {type: mushroom|triple|golden|red|blue|bullet|blooper, charges, expiresAt}
  carriedItem: null,
  setCarriedItem: (carriedItem) => set({ carriedItem }),
  // Item boxes on track: [{id, x, y, z, active, respawnAt}]
  itemBoxes: [],
  setItemBoxes: (itemBoxes) => set({ itemBoxes }),
  // Dropped live bombs: [{id, x, y, z, at}]
  droppedBombs: [],
  setDroppedBombs: (droppedBombs) => set({ droppedBombs }),
  // Explosions to render/react to: [{id, x, y, z, at}]
  explosions: [],
  setExplosions: (explosions) => set({ explosions }),
  // Live homing shells (red/blue): [{id, kind, x,y,z, dx,dz, targetId, owner, ownerId, at}]
  // Owner simulates + detects hits; remotes render the same entries.
  activeShells: [],
  setActiveShells: (activeShells) => set({ activeShells }),
  // Timestamp (performance.now) until which the kart is stunned.
  stunUntil: 0,
  setStunUntil: (stunUntil) => set({ stunUntil }),
  // Fresh session state: called on start/exit so stale boxes, live bombs,
  // explosions, carried bombs and stuns never leak into the next run.
  resetBattleState: () =>
    set({
      carriedBomb: false,
      carriedItem: null,
      activeShells: [],
      itemBoxes: [],
      droppedBombs: [],
      explosions: [],
      stunUntil: 0,
    }),
}));
